
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qjboemhffxyuddtwkyin.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFqYm9lbWhmZnh5dWRkdHdreWluIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1OTQ0MzksImV4cCI6MjA1OTE3MDQzOX0.UI_COubAoMovm8ffJWP1H-RObbS8NP7pntMeCIvpEY4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

export type Profile = {
  id: string;
  name: string | null;
  email: string | null;
  avatar_url: string | null;
  company: string | null;
  position: string | null;
  phone: string | null;
  created_at: string;
  updated_at: string;
};

export type CVReview = {
  id: string;
  user_id: string;
  cv_url: string;
  status: 'Pending' | 'In Review' | 'Completed';
  submitted_at: string;
  deadline: string;
  feedback: string | null;
  reviewer_id: string | null;
  created_at: string;
  updated_at: string;
};
